version: '3.9'

services:
  flask_server:
    container_name: flask_server
    image: sirsanctified/flask_server:0.0.1
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6500:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
